"""Physics-consistent multi-plane wavefront retrieval for the q=20 z-scan.

This module replaces the original notebook's "recover a phase at z0, fit it,
then propagate with absolute z labels" diagnostic.  It enforces one central
physical rule:

    all measured planes must be generated by propagation of ONE complex field
    at ONE reference plane.

The measured z-stack therefore constrains the longitudinal evolution of the
wavefront without inventing an independently adjustable phase for every z.
A phase correction remains a two-dimensional phase function at the plane where
it is applied; the corresponding x-y-z field is produced by wave propagation.

The module deliberately distinguishes:
  * total reconstructed phase,
  * nominal model phase,
  * residual phase = angle(U_retrieved * conj(U_nominal)), and
  * a virtual correction at the camera/reference plane.

The virtual correction is a diagnostic only.  It is NOT an SLM2 command until
the camera-to-SLM optical transform, magnification, parity/rotation, illuminated
footprint and phase LUT are calibrated.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

import numpy as np
from scipy import ndimage

try:
    from vbb_study.equations.fields import make_xy_grid
    from vbb_study.equations.propagation import (
        angular_spectrum_propagate_bl,
        make_bl_asm_propagator,
    )
except ModuleNotFoundError:  # direct execution from this folder
    import sys
    for _root in Path(__file__).resolve().parents:
        if (_root / "vbb_study").is_dir():
            sys.path.insert(0, str(_root))
            break
    from vbb_study.equations.fields import make_xy_grid
    from vbb_study.equations.propagation import (
        angular_spectrum_propagate_bl,
        make_bl_asm_propagator,
    )


EPS = 1.0e-12


@dataclass(frozen=True)
class RetrievalGrid:
    """Uniform square sampling used by the retrieval and propagation model."""

    n: int
    dx_m: float
    wavelength_m: float

    def grid(self) -> dict:
        return make_xy_grid(int(self.n), float(self.dx_m))


@dataclass
class MultiPlaneResult:
    """Result of one globally constrained multi-plane retrieval."""

    reference_field: np.ndarray
    z_positions_m: np.ndarray
    reference_index: int
    predicted_fields: list[np.ndarray]
    loss_history: np.ndarray
    plane_shape_errors: np.ndarray
    amplitudes: np.ndarray
    normalization_scales: np.ndarray
    metadata: dict

    @property
    def predicted_intensity(self) -> np.ndarray:
        return np.stack([normalise_intensity(np.abs(u) ** 2) for u in self.predicted_fields])


def normalise_intensity(image: np.ndarray) -> np.ndarray:
    image = np.clip(np.asarray(image, float), 0.0, None)
    return image / max(float(np.max(image)), EPS)


def unit_power_amplitude_from_intensity(image: np.ndarray) -> tuple[np.ndarray, float]:
    """Return sqrt(I) with unit L2 norm and the removed power scale.

    Plane-wise peak normalization distorts the amplitude constraint used by
    phase retrieval.  Unit-power normalization keeps the *shape* information
    while explicitly acknowledging that absolute inter-plane power cannot be
    trusted unless exposure/gain calibration is available.
    """

    intensity = np.clip(np.asarray(image, float), 0.0, None)
    power = float(np.sum(intensity))
    if power <= EPS:
        raise ValueError("phase retrieval received an empty intensity plane")
    amp = np.sqrt(intensity / power)
    return amp, power


def resize_square_preserving_fov(
    image: np.ndarray,
    output_n: int,
    *,
    center_yx: tuple[float, float] | None = None,
) -> np.ndarray:
    """Center a square image and resample it without changing physical FOV."""

    image = np.asarray(image, float)
    if image.ndim != 2:
        raise ValueError("expected one 2-D image")
    if center_yx is None:
        yy, xx = np.indices(image.shape)
        positive = np.clip(image, 0.0, None)
        positive = np.where(
            positive >= 0.02 * max(float(np.max(positive)), EPS), positive, 0.0
        )
        s = float(np.sum(positive))
        if s <= EPS:
            cy, cx = (np.asarray(image.shape, float) - 1.0) / 2.0
        else:
            cy = float(np.sum(yy * positive) / s)
            cx = float(np.sum(xx * positive) / s)
    else:
        cy, cx = map(float, center_yx)

    target = (np.asarray(image.shape, float) - 1.0) / 2.0
    shifted = ndimage.shift(
        image,
        shift=(target[0] - cy, target[1] - cx),
        order=1,
        mode="constant",
        cval=0.0,
        prefilter=False,
    )
    side = int(min(shifted.shape))
    y0 = (shifted.shape[0] - side) // 2
    x0 = (shifted.shape[1] - side) // 2
    square = shifted[y0:y0 + side, x0:x0 + side]

    output_n = int(output_n)
    if output_n < 16:
        raise ValueError("output_n is unreasonably small")
    if square.shape == (output_n, output_n):
        return square
    zoom = output_n / float(side)
    resized = ndimage.zoom(square, (zoom, zoom), order=1, prefilter=False)
    # scipy rounding can differ by one sample for unusual ratios
    if resized.shape != (output_n, output_n):
        resized = resized[:output_n, :output_n]
        if resized.shape != (output_n, output_n):
            pad_y = output_n - resized.shape[0]
            pad_x = output_n - resized.shape[1]
            resized = np.pad(resized, ((0, pad_y), (0, pad_x)))
    return resized


def prepare_amplitude_stack(
    images: Iterable[np.ndarray],
    *,
    output_n: int,
    native_pixel_pitch_m: float,
    centers_yx: Iterable[tuple[float, float] | None] | None = None,
) -> tuple[np.ndarray, float, np.ndarray]:
    """Prepare a shape-only amplitude stack on one common physical grid.

    The returned pixel pitch is scaled so the original crop field of view is
    preserved after resampling.
    """

    images = [np.asarray(im, float) for im in images]
    if not images:
        raise ValueError("no intensity planes supplied")
    native_side = int(min(images[0].shape))
    if any(min(im.shape) != native_side for im in images):
        raise ValueError("all planes must use a common field of view")
    if centers_yx is None:
        centers = [None] * len(images)
    else:
        centers = list(centers_yx)
        if len(centers) != len(images):
            raise ValueError("centers_yx must contain one entry per plane")

    amps: list[np.ndarray] = []
    scales: list[float] = []
    for image, center in zip(images, centers):
        small = resize_square_preserving_fov(image, int(output_n), center_yx=center)
        amp, power = unit_power_amplitude_from_intensity(small)
        amps.append(amp)
        scales.append(power)

    effective_dx_m = float(native_pixel_pitch_m) * native_side / float(output_n)
    return np.stack(amps), effective_dx_m, np.asarray(scales, float)


def choose_reference_index(z_positions_m: np.ndarray, amplitudes: np.ndarray) -> int:
    """Choose a central, information-rich reference plane.

    A central z minimizes the maximum propagation distance.  Among the three
    nearest planes to the median z, prefer the plane with the largest intensity
    variance, avoiding an almost featureless seed.
    """

    z = np.asarray(z_positions_m, float)
    if z.ndim != 1 or len(z) != len(amplitudes):
        raise ValueError("z_positions_m and amplitudes disagree")
    median = float(np.median(z))
    candidates = np.argsort(np.abs(z - median))[: min(3, len(z))]
    variances = [float(np.var(np.asarray(amplitudes[i]) ** 2)) for i in candidates]
    return int(candidates[int(np.argmax(variances))])


def _align_global_piston(candidate: np.ndarray, reference: np.ndarray) -> np.ndarray:
    overlap = np.vdot(reference.ravel(), candidate.ravel())
    if abs(overlap) <= EPS:
        return candidate
    return candidate * np.exp(-1j * np.angle(overlap))


def _propagate_from_reference(
    field_ref: np.ndarray,
    z_positions_m: np.ndarray,
    reference_index: int,
    retrieval_grid: RetrievalGrid,
) -> list[np.ndarray]:
    grid = retrieval_grid.grid()
    z = np.asarray(z_positions_m, float)
    z_ref = float(z[int(reference_index)])
    propagator = make_bl_asm_propagator(
        np.asarray(field_ref, complex),
        grid,
        float(retrieval_grid.wavelength_m),
        bandlimit=True,
        include_evanescent=False,
    )
    return [propagator(float(zj - z_ref)) for zj in z]


def amplitude_shape_error(predicted_field: np.ndarray, measured_amplitude: np.ndarray) -> float:
    """Unit-power RMS error of amplitude shape."""

    pred = np.abs(np.asarray(predicted_field, complex))
    pred /= max(float(np.linalg.norm(pred)), EPS)
    meas = np.asarray(measured_amplitude, float)
    meas /= max(float(np.linalg.norm(meas)), EPS)
    return float(np.sqrt(np.mean((pred - meas) ** 2)))


def multiplane_phase_retrieval(
    amplitudes: np.ndarray,
    z_positions_m: Iterable[float],
    retrieval_grid: RetrievalGrid,
    *,
    reference_index: int | None = None,
    initial_phase: np.ndarray | None = None,
    iterations: int = 160,
    relaxation: float = 0.65,
    support: np.ndarray | None = None,
    plane_weights: np.ndarray | None = None,
) -> MultiPlaneResult:
    """Recover ONE complex reference-plane field from all measured intensities.

    Each iteration propagates the *same* current reference field independently
    to every measured z plane, imposes that plane's measured amplitude, and
    back-propagates the constrained field to the common reference.  The coherent
    back-propagated estimates are then averaged.

    This is intentionally different from independently fitting a phase at every
    z.  Longitudinal phase evolution is supplied by the wave equation through
    band-limited angular-spectrum propagation.
    """

    amps = np.asarray(amplitudes, float)
    if amps.ndim != 3 or amps.shape[1] != amps.shape[2]:
        raise ValueError("amplitudes must have shape (planes, n, n)")
    if amps.shape[1] != int(retrieval_grid.n):
        raise ValueError("amplitude sampling does not match RetrievalGrid.n")
    z = np.asarray(list(z_positions_m), float)
    if z.ndim != 1 or len(z) != len(amps):
        raise ValueError("z_positions_m must contain one value per amplitude plane")
    if np.any(np.diff(z) <= 0):
        raise ValueError("z_positions_m must be strictly increasing")

    if reference_index is None:
        reference_index = choose_reference_index(z, amps)
    reference_index = int(reference_index)
    if not 0 <= reference_index < len(z):
        raise IndexError("reference_index out of range")

    if support is None:
        support = np.ones(amps.shape[1:], bool)
    else:
        support = np.asarray(support, bool)
        if support.shape != amps.shape[1:]:
            raise ValueError("support shape does not match images")

    if plane_weights is None:
        weights = np.ones(len(z), float)
    else:
        weights = np.asarray(plane_weights, float)
        if weights.shape != (len(z),):
            raise ValueError("plane_weights must contain one value per plane")
        if np.any(weights < 0) or float(np.sum(weights)) <= EPS:
            raise ValueError("plane_weights must be non-negative and not all zero")
    weights = weights / float(np.sum(weights))

    if initial_phase is None:
        phase0 = np.zeros(amps.shape[1:], float)
    else:
        phase0 = np.asarray(initial_phase, float)
        if phase0.shape != amps.shape[1:]:
            raise ValueError("initial_phase shape does not match images")

    U = amps[reference_index].astype(complex) * np.exp(1j * phase0)
    U[~support] = 0.0

    grid = retrieval_grid.grid()
    z_ref = float(z[reference_index])
    loss_history: list[float] = []

    for _iteration in range(int(iterations)):
        # One spectrum for the current common reference field.
        forward = make_bl_asm_propagator(
            U,
            grid,
            float(retrieval_grid.wavelength_m),
            bandlimit=True,
            include_evanescent=False,
        )

        back_sum = np.zeros_like(U, dtype=complex)
        shape_errors = []
        for weight, zj, amp_j in zip(weights, z, amps):
            dz = float(zj - z_ref)
            Uj = forward(dz)
            shape_errors.append(amplitude_shape_error(Uj, amp_j))

            constrained = amp_j * np.exp(1j * np.angle(Uj))
            if abs(dz) <= EPS:
                back = constrained
            else:
                back = angular_spectrum_propagate_bl(
                    constrained,
                    grid,
                    float(retrieval_grid.wavelength_m),
                    -dz,
                    bandlimit=True,
                    include_evanescent=False,
                )
            back_sum += float(weight) * back

        candidate = _align_global_piston(back_sum, U)
        # Enforce the measured reference-plane amplitude.  This fixes the
        # otherwise free amplitude scale while leaving phase as the unknown.
        candidate = amps[reference_index] * np.exp(1j * np.angle(candidate))
        candidate[~support] = 0.0

        relax = float(np.clip(relaxation, 0.0, 1.0))
        mixed = (1.0 - relax) * U + relax * candidate
        U = amps[reference_index] * np.exp(1j * np.angle(mixed))
        U[~support] = 0.0
        loss_history.append(float(np.mean(np.square(shape_errors))))

    predicted_fields = _propagate_from_reference(
        U, z, reference_index, retrieval_grid
    )
    plane_errors = np.asarray(
        [amplitude_shape_error(field, amp) for field, amp in zip(predicted_fields, amps)],
        float,
    )

    return MultiPlaneResult(
        reference_field=U,
        z_positions_m=z,
        reference_index=reference_index,
        predicted_fields=predicted_fields,
        loss_history=np.asarray(loss_history, float),
        plane_shape_errors=plane_errors,
        amplitudes=amps,
        normalization_scales=np.ones(len(z), float),
        metadata={
            "method": "global coherent multi-plane alternating projection",
            "propagator": "band-limited angular spectrum",
            "reference_z_m": float(z[reference_index]),
            "correction_dimensionality": "2-D phase at one physical plane; 3-D evolution by propagation",
            "hardware_ready": False,
        },
    )


def ideal_relative_phase(
    retrieved_field: np.ndarray,
    nominal_reference_field: np.ndarray,
    *,
    support: np.ndarray | None = None,
    smooth_sigma_px: float = 1.0,
    confidence_floor: float = 0.05,
) -> tuple[np.ndarray, np.ndarray]:
    """Return residual phase relative to the complete nominal complex field.

    Subtracting only ``q*theta`` is insufficient for a propagated Bessel field:
    radial Bessel sign changes, conical/curvature phase and ordinary propagation
    phase also belong to the nominal solution.  The residual is therefore the
    unit-phasor phase of ``U_retrieved * conj(U_nominal)``.

    Complex phasor smoothing avoids averaging wrapped angles directly.
    """

    u = np.asarray(retrieved_field, complex)
    nominal = np.asarray(nominal_reference_field, complex)
    if u.shape != nominal.shape:
        raise ValueError("retrieved and nominal fields must share a grid")

    amp_u = np.abs(u)
    amp_n = np.abs(nominal)
    confidence = (amp_u / max(float(amp_u.max()), EPS)) * (
        amp_n / max(float(amp_n.max()), EPS)
    )
    valid = confidence >= float(confidence_floor)
    if support is not None:
        valid &= np.asarray(support, bool)

    phasor = np.zeros_like(u, complex)
    phasor[valid] = (u[valid] / np.maximum(amp_u[valid], EPS)) * np.conj(
        nominal[valid] / np.maximum(amp_n[valid], EPS)
    )

    sigma = max(float(smooth_sigma_px), 0.0)
    if sigma > 0:
        w = ndimage.gaussian_filter(valid.astype(float) * confidence, sigma=sigma)
        re = ndimage.gaussian_filter(phasor.real * confidence, sigma=sigma)
        im = ndimage.gaussian_filter(phasor.imag * confidence, sigma=sigma)
        phasor = (re + 1j * im) / np.maximum(w, EPS)

    residual = np.full(u.shape, np.nan, float)
    residual[valid] = np.angle(phasor[valid])

    # Remove physically irrelevant global piston using a circular weighted mean.
    mean_phasor = np.sum(confidence[valid] * np.exp(1j * residual[valid]))
    piston = float(np.angle(mean_phasor)) if abs(mean_phasor) > EPS else 0.0
    residual[valid] = np.angle(np.exp(1j * (residual[valid] - piston)))
    return residual, confidence


def phase_screen_from_residual(residual_phase: np.ndarray, *, gain: float = 1.0) -> np.ndarray:
    """Return the conjugate residual phase, preserving invalid pixels as zero."""

    residual = np.asarray(residual_phase, float)
    correction = np.zeros_like(residual)
    valid = np.isfinite(residual)
    correction[valid] = -float(gain) * residual[valid]
    return correction


def apply_phase_screen(field: np.ndarray, phase_rad: np.ndarray) -> np.ndarray:
    field = np.asarray(field, complex)
    phase = np.asarray(phase_rad, float)
    if field.shape != phase.shape:
        raise ValueError("field and phase screen shapes differ")
    return field * np.exp(1j * phase)


def propagate_stack(
    reference_field: np.ndarray,
    z_positions_m: Iterable[float],
    reference_index: int,
    retrieval_grid: RetrievalGrid,
) -> list[np.ndarray]:
    """Public wrapper: all z planes come from the same reference field."""

    z = np.asarray(list(z_positions_m), float)
    return _propagate_from_reference(reference_field, z, int(reference_index), retrieval_grid)


def signed_longitudinal_sections(
    intensity_stack: np.ndarray,
    *,
    band_px: int = 2,
) -> tuple[np.ndarray, np.ndarray]:
    """Return fixed-coordinate x-z and y-z sections.

    No per-plane recentering is performed here.  Recentring would remove real
    beam-axis drift and must be an explicit, separately labelled morphology
    diagnostic rather than the default physical propagation view.
    """

    stack = np.asarray(intensity_stack, float)
    if stack.ndim != 3:
        raise ValueError("intensity_stack must have shape (z, y, x)")
    cy = stack.shape[1] // 2
    cx = stack.shape[2] // 2
    b = max(0, int(band_px))
    xz = stack[:, max(0, cy - b): min(stack.shape[1], cy + b + 1), :].mean(axis=1)
    yz = stack[:, :, max(0, cx - b): min(stack.shape[2], cx + b + 1)].mean(axis=2)
    return xz, yz


def recentered_morphology_stack(intensity_stack: np.ndarray) -> np.ndarray:
    """Return an explicitly recentered copy for shape-only diagnostics."""

    stack = np.asarray(intensity_stack, float)
    out = []
    target = (np.asarray(stack.shape[1:], float) - 1.0) / 2.0
    yy, xx = np.indices(stack.shape[1:])
    for image in stack:
        positive = np.clip(image, 0.0, None)
        s = float(np.sum(positive))
        if s <= EPS:
            out.append(image.copy())
            continue
        cy = float(np.sum(yy * positive) / s)
        cx = float(np.sum(xx * positive) / s)
        out.append(
            ndimage.shift(
                image,
                (target[0] - cy, target[1] - cx),
                order=1,
                mode="constant",
                cval=0.0,
                prefilter=False,
            )
        )
    return np.stack(out)


def field_from_nominal_propagator(
    nominal_field_at_known_plane: np.ndarray,
    *,
    nominal_plane_z_m: float,
    target_z_m: float,
    retrieval_grid: RetrievalGrid,
) -> np.ndarray:
    """Propagate a complete nominal complex field to the retrieval reference."""

    dz = float(target_z_m) - float(nominal_plane_z_m)
    return angular_spectrum_propagate_bl(
        np.asarray(nominal_field_at_known_plane, complex),
        retrieval_grid.grid(),
        float(retrieval_grid.wavelength_m),
        dz,
        bandlimit=True,
        include_evanescent=False,
    )
