"""Compose the A0 portrait PhD progress poster from current-code evidence.

The numerical panels are regenerated by ``build_phd_progress_poster.py`` and
this compositor combines them with the canonical committed q=20 experimental /
inverse evidence.  Layout iteration is deliberately kept separate from the
scientific calculations so visual changes cannot silently alter model results.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import textwrap
from typing import Mapping

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch, Polygon, Rectangle

import build_phd_progress_poster as source


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUT = ROOT / "outputs" / "poster" / "current_progress"

PAPER = "#f4f1e9"
WHITE = "#ffffff"
INK = "#14212b"
NAVY = "#102c3d"
NAVY_2 = "#173f50"
TEAL = "#0f8f8d"
TEAL_LIGHT = "#d9eeeb"
CORAL = "#df665d"
CORAL_LIGHT = "#f6dfda"
GOLD = "#d2a033"
PLUM = "#755684"
PLUM_LIGHT = "#e9e0ed"
MUTED = "#53636e"
LINE = "#cad1d1"


def _block(fig: plt.Figure, rect: tuple[float, float, float, float], face: str, *, edge: str | None = None, radius: float = 0.010) -> None:
    x, y, w, h = rect
    fig.patches.append(
        FancyBboxPatch(
            (x, y), w, h,
            boxstyle=f"round,pad=0.007,rounding_size={radius}",
            transform=fig.transFigure,
            facecolor=face,
            edgecolor=edge or face,
            linewidth=1.0,
            zorder=-2,
        )
    )


def _section(fig: plt.Figure, x: float, y: float, text: str, color: str, *, width: float = 0.16) -> None:
    fig.text(x, y, text.upper(), color=color, fontsize=24, weight="bold", va="bottom")
    fig.lines.append(plt.Line2D([x, x + width], [y - 0.004, y - 0.004], transform=fig.transFigure, color=color, lw=5, solid_capstyle="round"))


def _image(fig: plt.Figure, rect: tuple[float, float, float, float], path: Path | None, *, border: bool = False) -> None:
    ax = fig.add_axes(rect)
    ax.axis("off")
    if path is not None and path.is_file():
        ax.imshow(plt.imread(path))
    else:
        ax.text(0.5, 0.5, "figure unavailable", ha="center", va="center", color=MUTED, fontsize=18)
    if border:
        ax.add_patch(Rectangle((0, 0), 1, 1, transform=ax.transAxes, fill=False, edgecolor=LINE, linewidth=1.0))


def _cap(fig: plt.Figure, x: float, y: float, width: float, n: int, text: str, *, color: str = MUTED, size: float = 17.0) -> None:
    wrapped = textwrap.fill(text, width=max(42, int(width * 165)))
    fig.text(x, y, f"Fig. {n}. {wrapped}", color=color, fontsize=size, va="top", linespacing=1.18)


def _repo(path: str) -> Path | None:
    p = ROOT / path
    return p if p.is_file() else None


def _build_all_generated(out: Path) -> dict[str, Path]:
    out.mkdir(parents=True, exist_ok=True)
    generated: dict[str, Path] = {}
    builders = [
        ("self_healing", source.build_self_healing),
        ("sensitivity", source.build_sensitivity),
        ("source_to_sample", source.build_source_to_sample),
        ("v3_3d", source.build_v3_3d),
        ("structured", source.build_structured_gallery),
    ]
    for key, builder in builders:
        path, _ = builder(out)
        generated[key] = path
        print(f"[poster] built {key}: {path}")
    return generated


def compose(out: Path, generated: Mapping[str, Path]) -> tuple[Path, Path]:
    plt.rcParams.update({"font.family": "DejaVu Sans", "mathtext.fontset": "dejavusans"})
    fig = plt.figure(figsize=(33.11, 46.81), facecolor=PAPER)  # A0 portrait

    # Editorial scaffold - intentionally not a repeated three-column card grid.
    fig.patches.append(Rectangle((0.0, 0.884), 1.0, 0.116, transform=fig.transFigure, facecolor=NAVY, edgecolor="none", zorder=-5))
    fig.patches.append(Rectangle((0.0, 0.0), 0.012, 1.0, transform=fig.transFigure, facecolor=TEAL, edgecolor="none", zorder=-5))
    fig.patches.append(Polygon([[0.62, 0.884], [1.0, 0.884], [1.0, 0.790], [0.84, 0.817]], closed=True, transform=fig.transFigure, facecolor=NAVY_2, edgecolor="none", zorder=-4))
    fig.patches.append(Polygon([[0.0, 0.286], [0.56, 0.304], [1.0, 0.278], [1.0, 0.254], [0.34, 0.270], [0.0, 0.250]], closed=True, transform=fig.transFigure, facecolor="#e4eae6", edgecolor="none", zorder=-5))

    # Masthead.
    fig.text(0.044, 0.963, "DIGITAL-TWIN MODELLING AND INVERSE CORRECTION", color=WHITE, fontsize=52, weight="bold", va="top")
    fig.text(0.044, 0.927, "OF PROGRAMMABLE VORTEX-BESSEL BEAMLINES", color="#9de2dc", fontsize=45, weight="bold", va="top")
    fig.text(0.047, 0.894, "Samuel McKenna  |  Applied Optics & Photonics Group  |  Heriot-Watt University", color="#dbe6eb", fontsize=23, va="top")

    # Research aim / abstract.
    _section(fig, 0.045, 0.852, "Research aim", TEAL)
    _block(fig, (0.040, 0.727, 0.430, 0.108), WHITE, edge="#d6ddda")
    abstract = (
        "Programmable vortex-Bessel beams offer extended propagation and controllable transverse structure for ultrafast laser processing, but the field delivered by a real optical system can differ substantially from an ideal analytical beam. "
        "This work develops a physics-based numerical framework that follows the experimental route through two phase SLMs, explicit 4F order selection and a physical axicon. The same model is used to explore beam formation, robustness, parameter sensitivity and propagation through an optical interface. "
        "Crucially, the forward model is also used in reverse: multi-plane camera measurements are fitted to recover residual system/phase structure, construct a candidate SLM correction and forward-test that correction before hardware validation. The aim is a measurement-linked digital twin for diagnosis, correction and controlled beam delivery."
    )
    fig.text(0.057, 0.820, textwrap.fill(abstract, 88), color=INK, fontsize=21.5, va="top", linespacing=1.27)
    _block(fig, (0.058, 0.704, 0.392, 0.020), TEAL_LIGHT, radius=0.007)
    fig.text(0.074, 0.719, "DESIGN  ->  SIMULATE  ->  MEASURE  ->  INFER  ->  CORRECT  ->  VALIDATE", color=TEAL, fontsize=18.7, weight="bold", va="center")

    # Field model / numbered equations.
    _section(fig, 0.515, 0.852, "Field model", CORAL)
    _block(fig, (0.505, 0.701, 0.455, 0.134), CORAL_LIGHT, edge="#edc8c3")
    equations = [
        (r"$U_1(x,y)=U_G(x,y)\,\exp[i\ell\phi(x,y)]$", "(1)", 0.816, 27),
        (r"$U_2(x,y)=U_1(x,y)\,\exp[i\,2\pi f_c x]$", "(2)", 0.788, 27),
        (r"$U(z)=\mathcal{F}^{-1}\{\mathcal{F}[U(0)]e^{iz\sqrt{k^2-k_x^2-k_y^2}}\}$", "(3)", 0.759, 24),
        (r"$\hat{p}=\arg\min_p\sum_j d(I_j^{\mathrm{meas}},I_j^{\mathrm{model}}(p)),\quad \phi_{\mathrm{corr}}\approx-\widehat{\Delta\phi}$", "(4)", 0.730, 21),
    ]
    for eq, number, y, size in equations:
        fig.text(0.528, y, eq, color=INK, fontsize=size, va="top")
        fig.text(0.936, y, number, color=CORAL, fontsize=20, ha="right", va="top")
    fig.text(
        0.528, 0.704,
        "Eqs. (1-2) describe the programmable vortex and carrier phases; Eq. (3) propagates the complex field with the angular-spectrum transfer function. Eq. (4) summarises the inverse step: a parameterised forward model is fitted across measured z-planes and the recovered residual phase is tested as a conjugate correction.",
        color=MUTED, fontsize=16.4, va="bottom", linespacing=1.15,
    )

    # 1. Bench-matched route.
    _section(fig, 0.045, 0.672, "1  Physics-based optical route", TEAL, width=0.22)
    _image(fig, (0.045, 0.558, 0.910, 0.102), _repo("figures/presentation/01_computational_route_phase2j.png"))
    _cap(fig, 0.055, 0.552, 0.895, 1,
         "Current numerical route. The complex field is tracked through the same logical planes as the bench: input beam, SLM1, SLM2, explicit 4F order selection, physical refractive axicon and downstream propagation. Hardware effects are applied at the physical plane where they occur.", size=17.6)

    # 2. Broader modelling work.
    _section(fig, 0.045, 0.515, "2  Beam behaviour and design space", GOLD, width=0.24)
    _image(fig, (0.045, 0.409, 0.520, 0.094), generated.get("self_healing"))
    _cap(fig, 0.053, 0.402, 0.500, 2,
         "Self-healing benchmark regenerated from the maintained scalar engine. A local obstruction suppresses part of the field and the conical spectrum subsequently reconstructs it. Recovery is quantified against an unobstructed reference rather than inferred from one transverse image.", size=16.2)

    _block(fig, (0.590, 0.397, 0.365, 0.108), NAVY, edge=NAVY)
    _image(fig, (0.610, 0.413, 0.325, 0.078), generated.get("v3_3d"))
    _cap(fig, 0.607, 0.402, 0.330, 3,
         "Current-route V3 field at z=60 mm rendered as a transverse intensity surface. Height and colour encode the same intensity; this is not a fictitious propagation-volume rendering.", color="#dfe9ed", size=15.2)

    _image(fig, (0.045, 0.312, 0.340, 0.065), generated.get("sensitivity"), border=True)
    _cap(fig, 0.052, 0.306, 0.330, 4,
         "One-at-a-time sensitivity ranking. The calculation identifies parameters that strongly change the simulated Bessel region and therefore deserve tighter calibration; it does not assert that any ranked parameter is a dominant error in the current experiment.", size=14.8)

    _image(fig, (0.415, 0.313, 0.540, 0.063), generated.get("source_to_sample"))
    _cap(fig, 0.423, 0.306, 0.520, 5,
         "Source-to-sample optical model. The air-side field is handed explicitly across an interface and propagated in fused silica. This remains a planning-level optical calculation: intensity is not converted into an uncalibrated claim of ablation, index change or weld success.", size=14.8)

    # 3. Measurement-driven inverse correction. This is intentionally the dominant result area.
    _section(fig, 0.045, 0.262, "3  Measurement-driven inverse correction", PLUM, width=0.27)
    _block(fig, (0.035, 0.112, 0.930, 0.136), PLUM_LIGHT, edge="#d5c9db", radius=0.013)
    q20_main = _repo("figures/experimental/q20_aberration/single_mask/single_z_double_confirmation_minus10.png")
    q20_phase = _repo("figures/experimental/q20_aberration/reconstruction/annular_aberration_phase.png")
    q20_single = _repo("figures/experimental/q20_aberration/single_mask/single_mask_metrics_vs_z.png")
    q20_recreate = _repo("figures/experimental/q20_aberration/phase_error_recreation/phase_error_recreation_agreement_vs_z.png")

    _image(fig, (0.050, 0.156, 0.510, 0.079), q20_main)
    _cap(fig, 0.052, 0.147, 0.500, 6,
         "Measured q=20 inverse / forward confirmation at z=-10 mm. Measured camera data are experimental evidence; fitted or reconstructed fields and predicted corrected fields are model inference. A predicted corrected panel must not be read as a post-correction camera measurement.", color=INK, size=15.5)

    _image(fig, (0.585, 0.163, 0.175, 0.067), q20_phase)
    _image(fig, (0.775, 0.163, 0.170, 0.067), q20_single)
    fig.text(0.585, 0.154, "retrieved residual phase", color=PLUM, fontsize=15.5, weight="bold")
    fig.text(0.775, 0.154, "single-mask metrics vs z", color=PLUM, fontsize=15.5, weight="bold")

    _image(fig, (0.585, 0.119, 0.360, 0.031), q20_recreate)
    fig.text(
        0.585, 0.115,
        "Falsification / closure logic: the inferred error is forward-propagated and checked across z, rather than accepted because it matches one camera plane. The remaining experimental step is to apply the calibrated SLM correction and acquire a fresh z-stack.",
        color=INK, fontsize=14.6, va="top", linespacing=1.14,
    )

    # 4. Extensions, synthesis and references.
    _section(fig, 0.045, 0.092, "4  Extensions and next steps", CORAL, width=0.20)
    _image(fig, (0.045, 0.031, 0.335, 0.052), generated.get("structured"))
    _cap(fig, 0.048, 0.026, 0.325, 7,
         "A secondary modelling arm explores discrete N-fold and polygonal structured-beam families using the same propagation infrastructure.", size=13.8)

    fig.text(0.405, 0.086, "WHAT THE FRAMEWORK NOW DOES", color=TEAL, fontsize=19.5, weight="bold", va="top")
    fig.text(
        0.405, 0.075,
        "- reproduces the optical route rather than inserting an ideal output field\n"
        "- predicts signatures of controlled perturbations without pre-labelling them dominant\n"
        "- quantifies robustness, sensitivity and interface propagation\n"
        "- ingests multi-plane measurements for model fitting and phase reconstruction\n"
        "- forward-tests candidate corrections before experimental application",
        color=INK, fontsize=14.2, va="top", linespacing=1.30,
    )

    fig.text(0.710, 0.086, "REFERENCES", color=GOLD, fontsize=19.5, weight="bold", va="top")
    fig.text(
        0.710, 0.075,
        "[1] J. Durnin, J. Opt. Soc. Am. A 4, 651-654 (1987).\n"
        "[2] J. Durnin, J. J. Miceli Jr. & J. H. Eberly, Phys. Rev. Lett. 58, 1499-1501 (1987).\n"
        "[3] O. Brzobohaty, T. Cizmar & P. Zemanek, Opt. Express 16, 12688-12700 (2008).\n"
        "[4] S. Rao & G. K. Samanta, Opt. Lett. 43, 3029-3032 (2018).\n\n"
        "Code / numerical provenance: SamuelMcKena/Vortex-Bessel",
        color=INK, fontsize=14.0, va="top", linespacing=1.24,
    )

    fig.text(
        0.50, 0.004,
        "Claim boundary: model-only panels are numerical predictions; q=20 measured images are experimental evidence; retrieved phase and predicted-corrected fields remain model inference until verified by a fresh post-correction z-stack.",
        ha="center", va="bottom", color=MUTED, fontsize=11.8,
    )

    pdf = out / "Vortex_Bessel_PhD_Progress_Poster_A0_portrait.pdf"
    preview = out / "Vortex_Bessel_PhD_Progress_Poster_A0_portrait_preview.png"
    fig.savefig(pdf, format="pdf", facecolor=PAPER)  # exact A0 geometry; no tight bbox
    fig.savefig(preview, dpi=115, facecolor=PAPER)
    plt.close(fig)
    return pdf, preview


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args()
    out = args.out if args.out.is_absolute() else ROOT / args.out
    generated = _build_all_generated(out)
    pdf, preview = compose(out, generated)
    print(f"[poster] PDF: {pdf}")
    print(f"[poster] preview: {preview}")


if __name__ == "__main__":
    main()
